# user/keybinds.conf — tes raccourcis perso
# Nouveaux binds : ajoute simplement des lignes.
# Override d'un bind Caelestia posé en dur : unbind puis bind.

# bind = Super, G, exec, gimp
# bind = Super+Shift, S, exec, grimblast copy area

# unbind = Super, T
# bind = Super, T, exec, kitty

unbind = Super, G
bind = Super, G, exec, app2unit -- steam

bind = Super, O, exec, app2unit -- obsidian

bind = $kbCommunication, exec, app2unit -- vesktop