misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    background_color = 0x000000
}

input {
    kb_layout = fr
}

animations {
    enabled = false
}

decoration {
    blur {
        enabled = false
    }
}
